# Generated by Django 5.1.7 on 2025-04-13 08:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='section',
            new_name='api_section_branch__9cc7b4_idx',
            old_name='api_section_branch__33452f_idx',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='api_subject_branch__d7c3a9_idx',
            old_name='api_subject_branch__8755d3_idx',
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.semester'),
        ),
    ]
