# Generated by Django 4.2.10 on 2025-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_status_attendancedetail_is_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherleave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='teacherleave',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='attendancedetail',
            old_name='is_present',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='semester',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SubjectAssignment',
        ),
        migrations.DeleteModel(
            name='TeacherLeave',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
