# Generated by Django 5.2 on 2025-04-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_api_section_branch__33452f_idx_api_section_branch__9cc7b4_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentleaverequest',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='api_announc_branch__71d688_idx',
        ),
        migrations.RemoveIndex(
            model_name='internalmark',
            name='api_interna_student_8a9e04_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_student_2a6120_idx',
        ),
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together=set(),
        ),
    ]
