# Generated by Django 5.2 on 2025-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentleaverequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together={('student', 'subject', 'test_number')},
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['branch', 'created_at'], name='api_announc_branch__71d688_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmark',
            index=models.Index(fields=['student', 'subject'], name='api_interna_student_8a9e04_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', 'created_at'], name='api_notific_student_2a6120_idx'),
        ),
    ]
