# Generated by Django 4.2.10 on 2025-04-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_genericnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('subject', 'Subject'), ('section', 'Section'), ('private', 'Private'), ('faculty', 'Faculty')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='api.branch')),
                ('participants', models.ManyToManyField(limit_choices_to={'role__in': ('teacher', 'student', 'hod')}, related_name='chat_channels', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='api.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatchannel')),
                ('read_by', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ('teacher', 'student', 'hod')}, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(limit_choices_to={'role__in': ('teacher', 'student', 'hod')}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['channel', 'sent_at'], name='api_chatmes_channel_361eaf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatchannel',
            index=models.Index(fields=['branch', 'channel_type'], name='api_chatcha_branch__cd78cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatchannel',
            unique_together={('branch', 'name', 'channel_type')},
        ),
    ]
