# Generated by Django 4.2.10 on 2025-03-25 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role__in': ('teacher', 'hod')}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentleaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('teacher', 'hod')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_reviewed_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
