# Generated by Django 4.2.10 on 2025-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_leaverequest_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
